name: flutterprojectsample
description: A new Flutter application for quick develop application

version: 0.0.1+20200303

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #加密工具库
  crypto: ^2.1.3
  #用户配置存储
  shared_preferences: ^0.5.6+2
  #图片缓存
  cached_network_image: ^2.0.0
  #刷新组件
  flutter_easyrefresh: ^2.0.9
  #版本信息
  package_info: ^0.4.0+14
  # Cupertino Icons
  cupertino_icons: ^0.1.3
  #手机信息
  device_info: ^0.4.1+5
  #文件系统路径提供
  path_provider: ^1.6.4
  #链接跳转
  url_launcher: ^5.4.2
  #状态管理
  provider: ^4.0.4
  #数据库
  sqflite: ^1.2.1
  #网络请求
  dio: ^2.2.2
  #吐司
  fluttertoast: ^3.1.3
  #图片选择
  image_picker: ^0.6.3+4
  #日期格式化
  date_format: ^1.0.8
  #二维码生成
  qr_flutter: ^3.2.0
  #权限申请
  permission_handler: ^3.3.0
  #图片保存到相册
  image_gallery_saver: ^1.2.2
  #谁用谁闪亮
  shimmer: ^1.1.0
  #大图预览
  photo_view: ^0.5.0
  #解析Html标签
  flutter_html: ^0.11.1
  #路由框架
  fluro: ^1.5.2
  #屏幕适配
  flutter_screenutil: ^1.0.2
  #国际化
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  test: ^1.9.4

flutter:

  uses-material-design: true

  assets:
    - res/img/
    - res/img/2.0x/
    - res/img/3.0x/
    #以下是生成R文件的注释请不要删除
    # assets begin
    # res/img/*
    # assets end
    #以上是生成R文件的注释请不要删除

